version: '3.5'

services:

  php-fpm:
    container_name: xdebug-example-php-fpm-${APP_ENV:-dev}
    build:
      context: .
      target: ${APP_ENV:-dev}
      dockerfile: .docker/php-fpm/Dockerfile
      args:
        APP_ENV: ${APP_ENV:-dev}
        TZ: ${TZ:-Europe/Kiev}
    volumes:
      - ./:/var/www/html:rw
      - ~/.composer:/root/.composer/cache
    ports:
      - ${PHP_PORT:-8000}:8080
    command: 'composer serve'